### PR TITLE
Update to VTK Version 6.3

### PR DESCRIPTION
**Pull request by dmsurti**
This PR tests Mayavi compatibility with VTK 6.3 official release.

### CODE REVIEW

**Comment by opoplawski** [comment]
Seems to compile fine for me.

**Comment by dmsurti** [comment]
@prabhuramachandran Tested with VTK 6.3 which is now released. No further changes required to this PR. Please review/merge.

**Comment by jenshnielsen** [comment]
Any progress on merging this?

**Comment by prabhuramachandran** [comment]
Sorry folks, I will look at this the coming week.

**Comment by prabhuramachandran** [comment]
@dmsurti -- I think the PR #250  subsumes this and should resolve all of these issues as well, so if you can review that PR and merge it these should be resolved.

**Comment by prabhuramachandran** [comment]
@dmsurti -- can we close this?  I think the master version should fix all these issues.

**Comment by dmsurti** [comment]
Closed as #250 supersedes this. 

Pending issue #279 should be fixed in a new PR.

**Pull request closed without merging**
