### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by prabhuramachandran**
The aim of this PR is to solicit feedback and merge this early for those who want to cut themselves on the bleeding edge.  

This adds experimental Python3 support for Mayavi.  To use it one requires a recent version of apptools and envisage (by recent I mean that these PRs should be merged https://github.com/enthought/apptools/pull/54 and https://github.com/enthought/envisage/pull/61 ).

It requires the master branch of pyface. 

It will require the latest version of VTK from their git repository (https://gitlab.kitware.com/vtk/vtk) and a fresh build of VTK configured for Python3.  I have not bothered with travis CI support at this point due to the complexity of doing that.  These changes pass all current 2.7.x tests on travis so should be safe to merge.

## Status and known issues

 * The changes are compatible with Python 2.x and 3.x.  I have tested on 2.7.x and 3.4.x.

 * All the tvtk tests pass.

 * There are a couple of random failures in the mayavi tests.  These may be version specific issues but need more investigation.

 * The integration tests mostly run fine but blocks on exit (with PyQt) so if you run one of them you need to kill it to run the next.  This can be investigated later.

 * mlab works quite well.

 * The mayavi2 application itself has a few issues that seem pyface related and will be investigated later, notably the persistence of the workbench perspectives are not pickled/unpickled properly..

### CODE REVIEW

**Comment by mabl** [comment]
While I still have not got this to work, I've run into some small issues
```
Sorry: TabError: inconsistent use of tabs and spaces in indentation (qt_gradient_editor.py, line 75)
  File "/home/mabl/PhD/Software/virtualenv3.5/lib/python3.5/site-packages/mayavi-4.4.3-py3.5-linux-x86_64.egg/tvtk/pyface/ui/wx/wxVTKRenderWindowInteractor.py", line 48
    True = 1
```

The call to build the docs fails on 
```python
execfile(os.path.join('..', '..', '..', 'mayavi', '__init__.py'), d)
```

**Comment by mabl** [comment]
When I work around the doc issue, I can install it, but it will not import mlab:

```
>>> import mayavi
>>> import mayavi.mlab
Traceback (most recent call last):
  File "tvtk_classes/tvtk_helper.py", line 23, in get_module
ImportError: No module named 'tvtk.custom.light'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/mayavi/mayavi/mlab.py", line 27, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/tmp/mayavi/mayavi/tools/camera.py", line 25, in <module>
    from .engine_manager import get_engine
  File "/tmp/mayavi/mayavi/tools/engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "/tmp/mayavi/mayavi/core/engine.py", line 28, in <module>
    from mayavi.core.base import Base
  File "/tmp/mayavi/mayavi/core/base.py", line 19, in <module>
    from tvtk.pyface.tvtk_scene import TVTKScene
  File "/tmp/mayavi/tvtk/pyface/tvtk_scene.py", line 27, in <module>
    from tvtk.pyface import light_manager
  File "/tmp/mayavi/tvtk/pyface/light_manager.py", line 130, in <module>
    class CameraLight(HasTraits):
  File "/tmp/mayavi/tvtk/pyface/light_manager.py", line 146, in CameraLight
    source = Instance(tvtk.Light, ())
  File "tvtk_classes/tvtk_helper.py", line 225, in <lambda>
  File "tvtk_classes/tvtk_helper.py", line 36, in get_class
  File "tvtk_classes/tvtk_helper.py", line 28, in get_module
  File "tvtk_classes/light.py", line 10, in <module>
  File "/tmp/mayavi/tvtk/array_handler.py", line 28, in <module>
    from tvtk.array_ext import set_id_type_array
ImportError: No module named 'tvtk.array_ext'
```

**Comment by prabhuramachandran** [comment]
@mabl -- thanks for picking those issues, I've pushed fixes for them now.

**Comment by prabhuramachandran** [comment]
@mabl -- As regards the bug, I suspect your mayavi build did not complete and array_ext was not built.

**Comment by mabl** [comment]
Hi @prabhuramachandran,

still no success for me, unfortunately. A small collection of issues I've seen with the current code:

```
Exception occurred:
  File "/usr/lib/python3.5/site-packages/sphinx/application.py", line 429, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/home/mabl/tmp/vtk/mayavi/docs/source/mayavi/sphinxext/traitsdoc.py", line 129
    print "[numpydoc] Phantom importing modules from", fn, "..."
                                                    ^
SyntaxError: Missing parentheses in call to 'print'
```

```
  File "build/bdist.linux-x86_64/egg/tvtk/pyface/ui/wx/wxVTKRenderWindowInteractor.py", line 48
    True = 1
       ^
SyntaxError: can't assign to keyword
```

The array_ext problem continues, I'll have to try further.

**Comment by mabl** [comment]
I'm also seeing other errors:

```
>>> import mayavi.mlab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mabl/tmp/vtk/mayavi/mayavi/mlab.py", line 27, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/home/mabl/tmp/vtk/mayavi/mayavi/tools/camera.py", line 25, in <module>
    from .engine_manager import get_engine
  File "/home/mabl/tmp/vtk/mayavi/mayavi/tools/engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "/home/mabl/tmp/vtk/mayavi/mayavi/core/engine.py", line 34, in <module>
    from mayavi.core.ui.mayavi_scene import viewer_factory
  File "/home/mabl/tmp/vtk/mayavi/mayavi/core/ui/mayavi_scene.py", line 12, in <module>
    from tvtk.tools.ivtk import IVTK
  File "/home/mabl/tmp/vtk/mayavi/tvtk/tools/ivtk.py", line 35, in <module>
    from tvtk.pyface.api import Scene, DecoratedScene
  File "/home/mabl/tmp/vtk/mayavi/tvtk/pyface/api.py", line 1, in <module>
    from .decorated_scene import DecoratedScene
  File "/home/mabl/tmp/vtk/mayavi/tvtk/pyface/decorated_scene.py", line 13, in <module>
    DecoratedScene = toolkit_object('decorated_scene:DecoratedScene')
  File "/home/mabl/tmp/vtk/mayavi/tvtk/pyface/toolkit.py", line 92, in toolkit_object
    __import__(be_mname)
  File "/home/mabl/tmp/vtk/mayavi/tvtk/pyface/ui/qt4/decorated_scene.py", line 23, in <module>
    from .scene import Scene
  File "/home/mabl/tmp/vtk/mayavi/tvtk/pyface/ui/qt4/scene.py", line 39, in <module>
    from .QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
  File "/home/mabl/tmp/vtk/mayavi/tvtk/pyface/ui/qt4/QVTKRenderWindowInteractor.py", line 39, in <module>
    pythonapi.PyCObject_AsVoidPtr.restype = c_void_p
  File "/usr/lib64/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: PyCObject_AsVoidPtr
```
Maybe because I'm on Python 3.5?

And a small numpy api warning:
```
creating build/temp.linux-x86_64-3.5/tvtk/src
compile options: '-I/usr/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -I/usr/include/python3.5m -c'
gcc: tvtk/src/array_ext.c
In file included from /usr/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:0,
                 from /usr/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from tvtk/src/array_ext.c:223:
/usr/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-3.5/tvtk/src/array_ext.o -L/usr/lib -lpython3.5m -o tvtk/array_ext.cpython-35m-x86_64-linux-gnu.so
```

**Comment by mabl** [comment]
HI all, I'm wondering if there was any more progress on this. I'd like to fulfill my last new year resolution to switch over to python 3 completely :-)

**Comment by prabhuramachandran** [comment]
@mabl -- Sorry for the delay.  I have made a few changes, do these changes fix the last of the issues you were facing?

**Comment by mabl** [comment]
@prabhuramachandran This works! Thank you so much!  A simple 
```
pip install --upgrade git+https://github.com/prabhuramachandran/mayavi.git@feature/python3
```
was enough (the dependencies were already up-to-date). You have my vote to get that merged.

**Comment by prabhuramachandran** [comment]
@mabl -- thanks for testing this!  You should actually use the https://github.com/enthought/mayavi.git repositories feature/python3 branch as it is the main one.  Will ask @dmsurti to do a review and merge this ASAP.

**Comment by dmsurti** [comment]
@prabhuramachandran The appveyor failure is due to this known issue, #233.

Needs a docs updated in a separate PR: Issue #274. Also issues need to be opened for known issues listed in the PR description. The other issues need to be opened for: Updating CI for both py2/py3.

My only question is around why we did not use a tool (modernize/futurize) to update the code? But otherwise LGTM.

Once the issues are listed, which I will do later, I will merge this!!!

**Comment by dmsurti** [comment]
@prabhuramachandran All known issues have been logged. Will you be pushing more updates to this PR?

**Comment by prabhuramachandran** [comment]
@dmsurti -- No, nothing planned for now.  It would be good to have this merged and then work on the other issues slowly.  We could potentially put out a release as I think this resolves a bunch of issues with recent VTK versions.

**Comment by dmsurti** [comment]
LGTM. Thanks @prabhuramachandran.

**Comment by jeremyherbert** [comment]
I currently can't get this to work using the git master:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-c7e202e132f1> in <module>()
----> 1 import mayavi.mlab

/Users/jeremy/anaconda/lib/python3.5/site-packages/mayavi/mlab.py in <module>()
     25
     26 # Mayavi imports
---> 27 from mayavi.tools.camera import view, roll, yaw, pitch, move
     28 from mayavi.tools.figure import figure, clf, gcf, savefig, \
     29     draw, sync_camera, close, screenshot

/Users/jeremy/anaconda/lib/python3.5/site-packages/mayavi/tools/camera.py in <module>()
     23 # We can't use gcf, as it creates a circular import in camera management
     24 # routines.
---> 25 from .engine_manager import get_engine
     26
     27

/Users/jeremy/anaconda/lib/python3.5/site-packages/mayavi/tools/engine_manager.py in <module>()
     10
     11 # Local imports
---> 12 from mayavi.preferences.api import preference_manager
     13 from mayavi.core.registry import registry
     14 from mayavi.core.engine import Engine

/Users/jeremy/anaconda/lib/python3.5/site-packages/mayavi/preferences/api.py in <module>()
      2
      3 # The global PreferenceManager instance
----> 4 from .preference_manager import preference_manager
      5 from .bindings import set_scene_preferences, get_scene_preferences

/Users/jeremy/anaconda/lib/python3.5/site-packages/mayavi/preferences/preference_manager.py in <module>()
     28 from traits.api import HasTraits, Instance
     29 from traitsui.api import View, Group, Item
---> 30 from apptools.preferences.api import (ScopedPreferences, IPreferences,
     31         PreferencesHelper)
     32

/Users/jeremy/anaconda/lib/python3.5/site-packages/apptools/preferences/api.py in <module>()
----> 1 from i_preferences import IPreferences
      2
      3 from package_globals import get_default_preferences, set_default_preferences
      4 from preferences import Preferences
      5 from preference_binding import PreferenceBinding, bind_preference

ImportError: No module named 'i_preferences'
```

I'm using anaconda python 3.5 on OSX. VTK is built and I can import it successfully. I installed this by downloading the zip of the repo, and running pip install on it. Any help would be appreciated.

**Comment by jeremyherbert** [comment]
Never mind, I worked it out.

For anyone else, assuming you like to live life on the edge, you need to pip install 

https://github.com/enthought/apptools/archive/master.zip
https://github.com/enthought/envisage/archive/master.zip

**Comment by solarjoe** [comment]
Just some quick postive feedback
I am using WinPython-64bit-3.4.4.1 with Mayavi and it works fine. Thanks to all devs!

1.) VTK-7.0.0-cp34-cp34m-win_amd64.whl (http://www.lfd.uci.edu/~gohlke/pythonlibs/#vtk)
2.) pip install mayavi

**Comment by indranilsinharoy** [comment]
@solarjoe 
Hi, 
I was really excited seeing your feedback, as I have not been able to install Mayavi properly lately. 

I installed WinPython-64bit-3.4.4.1, following which I downloaded VTK-7.0.0-cp34-cp34m-win_amd64.whl from the above link. However,, when I try to install VTK using the WinPython control panel, I get the following error message:

```
The following packages filenaming are not recognized by WinPython Control Panel: VTK-7.0.0-cp34-cp34m-win_amd64.whl
```

My environment is 64 bit, Windows 7. Did you ever see the above error, or would you know how to resolve this issue? Any suggestions will be useful.

Thank you very much.
Regards,
Indranil.

**Comment by solarjoe** [comment]
Hello @indranilsinharoy,

yes, I also came across that issue, it should be fixed in the next WinPython release.
As a workaround I did what is mentioned here:
https://github.com/winpython/winpython/issues/258

Other workarounds to fix the naming detection are listed here:
https://github.com/winpython/winpython/issues/303
https://github.com/winpython/winpython/pull/260

Or you can rename the package, I guess VTK-7.0.0-cp34-none-win_amd64.whl
should work. But I recommend some of the other suggestions to fix it permanently.

Have fun with Mayavi!

**Comment by indranilsinharoy** [comment]
@solarjoe ,

Thank you very much. The first solution worked out rather well for WinPython-64bit-3.4.4.1. 

Interestingly, since I already had WinPython-64bit-3.5.1.1 I was eager to test the solution on  WinPython-64bit-3.5 (that want I wouldn't need to keep two version of WinPython). For whatever reason, I couldn't get VTK-7.0.0-cp35-cp35m-win_amd64.whl to install. So, for now I will just stick with WinPython-64bit-3.4.4.1.

**Pull request merged**
