### PR TITLE
Revert "Fix savefig size and black image"

### PR DESCRIPTION
**Pull request by kitchoi**
Reverts enthought/mayavi#331
This should not be merged yet.

### CODE REVIEW

**Comment by stefanoborini** [comment]
oh ok... sorry, but does it work?

**Comment by kitchoi** [comment]
Works except when on-screen + the size of image requested is larger than my physical screen resolution.  It wasn't captured in the test_mlab_savefig.py as the image size was not big enough, and was only recently discovered (today)

**Comment by stefanoborini** [comment]
Ok. Merging when green, please restore the branch and PR for the other one. Leave it [WIP]

**Comment by kitchoi** [comment]
Appveyor has hung but Travis passed.  I will proceed with the revert now (sooner the better).

**Pull request merged**
