### PR TITLE
pkg_resources is deprecated in favor of importlib.resources

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Review by prabhuramachandran — CHANGES_REQUESTED** [review]
Many thanks for this, this conflicts with the recent changes from #1315, could you please update this and I can merge the fix?  Thank you.

**Comment by mr-c** [comment]
Thank you @prabhuramachandran ; I rebased the PR

**Review by prabhuramachandran — APPROVED** [review]
Looks fine except I am unable to keep track of the changes between Python versions and our minimum requirement.

**Comment by prabhuramachandran** [comment]
@mr-c -- could you please rebase this so we can run the checks.

**Pull request merged**
