### PR TITLE
add matrix build for vtk 6.3 and vtk 7.0 on appveyor

### PR DESCRIPTION
**Pull request by itziakos**

### CODE REVIEW

**Comment by itziakos** [comment]
The tests for vtk 7.0 segfault on appveyor.

**Comment by prabhuramachandran** [comment]
@itziakos -- thanks for this, can you please update this PR when you have a moment?  Do you wish to do anything different or change something?

**Comment by itziakos** [comment]
it have been a while, I will try to revisit this PR by the end of the week.

**Comment by prabhuramachandran** [comment]
@itziakos -- thanks a ton!  There are also more recent versions of VTK that we should use 8.0 is out as is 7.1.1 and I think we should really use those instead if at all possible.

**Comment by itziakos** [comment]
@prabhuramachandran I have updated the PR and changed it to install vtk 7.1.  

Please note that this setup is simple and fast because it uses the official vtk binaries and manipulates the path so that the vtk extension modules are visible by the default python. The current setup cannot use VTK 8 since there is no available binary for VTK 8.

However, the issue is still the same as before the tests for 7.1. segfault. The possible reasons for this segfault:

(a) The python extension modules in the vtk binaries are not compatible with the used python. Although the method works for vtk 6.3
(b) This is a real mayavi bug that causes the garbage collection to fail
(c) There is a hidden VTK error that is exposed by the mayavi tests.

**Comment by itziakos** [comment]
```python
Tests if TVTK scene can be garbage collected. ... Fatal Python error: Segmentation fault

Current thread 0x00000930 (most recent call first):
  File "tvtk_classes\render_window_interactor.py", line 885 in initialize
  File "C:\projects\mayavi\tvtk\pyface\tvtk_scene.py", line 830 in _create_control
  File "C:\projects\mayavi\tvtk\pyface\tvtk_scene.py", line 209 in __init__
  File "C:\projects\mayavi\tvtk\tests\test_garbage_collection.py", line 21 in create_fn
  File "C:\projects\mayavi\tvtk\tests\common.py", line 49 in do
  File "C:\projects\mayavi\tvtk\tests\common.py", line 58 in check_object_garbage_collected
  File "C:\projects\mayavi\tvtk\tests\test_garbage_collection.py", line 26 in test_tvtk_scene
  File "c:\python27-x64\lib\unittest\case.py", line 329 in run
  File "c:\python27-x64\lib\unittest\case.py", line 393 in __call__
  File "c:\python27-x64\lib\site-packages\nose\case.py", line 151 in runTest
  File "c:\python27-x64\lib\site-packages\nose\case.py", line 133 in run
  File "c:\python27-x64\lib\site-packages\nose\case.py", line 45 in __call__
  File "c:\python27-x64\lib\site-packages\nose\suite.py", line 224 in run
  File "c:\python27-x64\lib\site-packages\nose\suite.py", line 177 in __call__
  File "c:\python27-x64\lib\site-packages\nose\suite.py", line 224 in run
  File "c:\python27-x64\lib\site-packages\nose\suite.py", line 177 in __call__
  File "c:\python27-x64\lib\site-packages\nose\suite.py", line 224 in run
  File "c:\python27-x64\lib\site-packages\nose\suite.py", line 177 in __call__
  File "c:\python27-x64\lib\site-packages\nose\suite.py", line 224 in run
  File "c:\python27-x64\lib\site-packages\nose\suite.py", line 177 in __call__
  File "c:\python27-x64\lib\site-packages\nose\core.py", line 62 in run
  File "c:\python27-x64\lib\site-packages\nose\core.py", line 207 in runTests
  File "c:\python27-x64\lib\unittest\main.py", line 95 in __init__
  File "c:\python27-x64\lib\site-packages\nose\core.py", line 121 in __init__
  File "c:\python27-x64\lib\site-packages\nose\core.py", line 341 in <module>
  File "c:\python27-x64\lib\site-packages\coverage\execfile.py", line 183 in run_python_file
  File "c:\python27-x64\lib\site-packages\coverage\execfile.py", line 113 in run_python_module
  File "c:\python27-x64\lib\site-packages\coverage\cmdline.py", line 621 in do_run
  File "c:\python27-x64\lib\site-packages\coverage\cmdline.py", line 486 in command_line
  File "c:\python27-x64\lib\site-packages\coverage\cmdline.py", line 750 in main
  File "C:\Python27-x64\scripts\coverage.exe\__main__.py", line 9 in <module>
  File "c:\python27-x64\lib\runpy.py", line 72 in _run_code
  File "c:\python27-x64\lib\runpy.py", line 174 in _run_module_as_main
Command exited with code -1073741819
```

**Comment by prabhuramachandran** [comment]
@itziakos -- can I close this PR as it is now very old and superseded by some recent changes.

**Comment by itziakos** [comment]
@prabhuramachandran please note that tests on appveyor build only against the latest vtk available through edm which at the moment is `7.0.0`.

**Comment by prabhuramachandran** [comment]
@itziakos -- I've changed all that and the appveyor tests currently run on Python 3.6 using VTK-8.1 from pypi and PyQt5.

**Pull request closed without merging**
