### PR TITLE
avoid loading nbextension via absolute URL

### PR DESCRIPTION
**Pull request by minrk**
1. load x3dom CDN over HTTPS
2. never load nbextensions with an absolute path, which only works when there is no base url (won't work in JupyterHub)

### CODE REVIEW

**Comment by prabhuramachandran** [comment]
@minrk -- thanks, this is a busy week for me.  I will take a look at this and other pending PRs next week or more likely week after that when my teaching duties end.

**Comment by kwotuveang3k4bk** [comment]
I am sorry, but I do not see how https://www.x3dom.org/download/ should work, should not it be: https://www.x3dom.org/download/1.7.2/ ?

**Comment by kwotuveang3k4bk** [comment]
But the relative path also does not work for me, I get:
`/user/username/notebooks/path/to/my/notebook/and/notebook/name/nbextensions/mayavi/x3d/x3dom.js`
but it should be: 
`/user/username/nbextensions/mayavi/x3d/x3dom.js`
and previously it was: 
`/nbextensions/mayavi/x3d/x3dom.js`

Can anyone confirm this change is working with Jupyterhub?

**Comment by minrk** [comment]
I was able to test with JupyterHub just now. I had to also remove the `.js` extension from the require string (require shouldn't be passed `.js`, just like Python import shouldn't get `.py`), but now it definitely works.

**Comment by prabhuramachandran** [comment]
Thanks, LGTM, merging for now.

**Pull request merged**
